name: 'pipeline_engineering_framework'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'pipeline_engineering_framework'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/reference/model-configs
models:
  pipeline_engineering_framework:
    # Config indicated by + and applies to all files under models/example/
    +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table
      +schema: marts

# Configuring tests
tests:
  pipeline_engineering_framework:
    +store_failures: true
    +schema: test_failures

